download:
	@python3 main.py download
clear:
	@python3 main.py clear
	@echo "all files are deleting"
list:
	@echo "files are listed and can be shown in songs.json"
	@python3 main.py list
insert:
	@python3 main.py insert
	@echo "inserting files to database"
diff:
	@echo "diffing files"
	@python3 main.py diff
