download:
	@python3 main.py download
clear:
	@python3 main.py clear
	@echo "all files are deleting"
list:
	@python3 main.py list
	@echo "files are listed and can be shown in songs.json"
insert:
	@python3 main.py insert
	@echo "inserting files to database"
